### ISSUE TITLE
ref и reactive

### ISSUE THREAD

**Issue by webPrsnr** [vuesence/vue-faq#1]
https://vue-faq.org/development/misc.html

> Ref на объекте использует напрямую Reactive, **_а для примитивов оборачивает их в объект и снова использует Reactive_**.

Разве это так?
В конструкторе класса [`RefImpl`](https://github.com/vuejs/core/blob/b775b71c788499ec7ee58bc2cf4cd04ed388e072/packages/reactivity/src/ref.ts#L131) в условии есть функция [`toReactive`](https://github.com/vuejs/core/blob/b775b71c788499ec7ee58bc2cf4cd04ed388e072/packages/reactivity/src/ref.ts#L146C43-L146C53). [Которая](https://github.com/vuejs/core/blob/b775b71c788499ec7ee58bc2cf4cd04ed388e072/packages/reactivity/src/reactive.ts#L406) в свою очередь принимает примитив и возвращает примитив.

**Comment by altrusl** [comment]
Да, действительно, ошибка
Исправил
