### ISSUE TITLE
wrong link to  w3schools.com 

### ISSUE THREAD

**Issue by jtprof** [vuesence/vue-faq#28]
The link in text 'На сайте [w3school.com](http://w3school.com/) предлагается бесплатный CSS фреймворк' In section
https://vue-faq.org/ru/book/Chapter_3__Setting_Up_a_Working_Project.html#фреимворк-w3-css
is shown to insecure site 'http://w3school.com'

**Comment by altrusl** [comment]
Fixed
Thanks
