### ISSUE TITLE
Пару ошибок которые есть в написанном коде для примеров использования Pinia. Я джуниор, но без них у меня код не работал.

### ISSUE THREAD

**Issue by SadBatya** [vuesence/vue-faq#34]
//Composition API
import {ref,computed} from 'vue'                          //1
import {defineStore} from 'pinia'
const useCounterStore=defineStore('counter',()=>{        
 //Также на данной строке забыли экспортировать store и при импорте вью ругается и не видит его
  export const useCounterStore - добавляем обычный export и после этого все начинает работать

    const
        count = ref(0),                                   //3
        in_range=ref(true),
        doubleCount = computed(() => {                    //4
             if(count.value>=0){
                 return count.value *2;
             }else{
                 return 0
        }}),
        inRange = computed(()=>return count.value>=0); // В данном месте вы забыли фигурные скобки, и поэтому линтер ругается
        // Исправленная строка должна выглядеть так 
        nRange = computed(()=>{ 
           return {
            count.value>=0
          }})
    function increment() {count.value++}                  //5
    function decrement(){count.value--;}
    return {                                              //6
        count, doubleCount, inRange,
        increment, decrement
    }
})

**Comment by altrusl** [comment]
Fixed
